### ISSUE TITLE
Compilation error from `stencil build --watch`

### ISSUE THREAD

**Issue by R-Bower** [arthur-fontaine/stencil-vanilla-extract-plugin#1]
Reproduction: https://github.com/R-Bower/stencil-vanilla-extract-error-reproduction

Frequently, when I edit the render() function of a class that uses vanilla-extract styles, I see an error message + failed compilation:
```
[ ERROR ]  Rollup: Unresolved Import
           Could not resolve './badge.css?tag=uc-badge'
           from ./src/components/badge/badge.tsx

[03:48.0]  rebuild failed, watching for changes... in 2.77
           s
```

Follow the reproduction steps in the repo's readme to produce the issue.

**Comment by peterbartels** [comment]
What if you change it to `styleUrls: ["badge.css.ts"]`? It seems to work.
@R-Bower @arthur-fontaine

**Comment by arthur-fontaine** [comment]
Tested and it works @peterbartels. I will update the documentation.

Also, this issue maybe related to https://github.com/ionic-team/stencil/issues/2840?
